In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import _tconfint_generic as t_stat

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array( [401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [3]:
M_X = zp.mean()
M_Y = ks.mean()
M_XY = (zp * ks).mean()

In [4]:
cov_ks = M_XY - M_X * M_Y
cov_ks

9157.839999999997

In [5]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [6]:
np.cov(zp, ks, ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [7]:
std_X = zp.std()
std_Y = ks.std()

In [8]:
corr_ks = cov_ks / (std_X * std_Y)
corr_ks

0.8874900920739158

In [9]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [10]:
X = np.array([131.0, 125.0, 115.0, 122.0, 131.0, 115.0, 107.0, 99.0, 125.0, 111.0])
mean_X = X.mean()
std_X = X.std(ddof=1)
mean_std_X = std_X / (np.sqrt(len(X)))

In [11]:
t_stat(mean_X, mean_std_X,len(X) - 1, 0.05, 'two-sided')

(110.55608365158724, 125.64391634841274)

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [15]:
b=25
n=27
mu=174.2
alpha=0.95

#для alpha=0.95
z=1.96

x1=mu-z*(b/np.sqrt(n))
x2=mu+z*(b/np.sqrt(n))
x1,x2

(164.7699456032361, 183.63005439676388)